sudo: required

language: go

go:
  - 1.10.1

services:
  - docker

cache:
  directories:
    - vendor/

env:
  global:
    - CGO_ENABLED=0
    - GOBUILD="linux-amd64"

script:
  - make -j dist
  - ls -la build

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file:
    - build/docker-mirror-linux-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/docker-mirror
