---
cleanup: true

target:
  registry: 847030493009.dkr.ecr.us-east-2.amazonaws.com
  prefix: "hub/"

repositories:
  - name: redis
    max_tag_age: 4w
    match_tag:
        - "3*"
        - "4*"
        - "latest"
    ignore_tag:
      - "*32bit*"
      - "*alpine*"
      - "*nanoserver*"
      - "*windowsservercore*"

  - name: kubebuilder/kube-rbac-proxy
    host: gcr.io
    match_tag:
      - "v*"
