name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.23
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build
      run: make -j dist
    - name: Test
      run: go test -timeout=600s -v
    - name: List output
      run: ls -la build
